name: opencode
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    if: |
      (contains(github.event.comment.body, '/oc') || contains(github.event.comment.body, '/opencode')) &&
      github.event.comment.user.type != 'Bot'
    runs-on: ubuntu-latest
    permissions:
      id-token: write      
      contents: write      
      pull-requests: write 
      issues: write        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Run OpenCode
        uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENCODE_VERSION: "1.18.32"
          OPENCODE_DISABLE_PERMISSION_ASSERT: "true"
          OPENCODE_MODEL: "openai/gpt-5.4-nano"
          OPENCODE_SMALL_MODEL: "openai/gpt-5.4-nano"
        with:
          # Usamos el identificador exacto que te sugiere el servidor
          model: openai/gpt-5.4-nano
          use_github_token: false
